[2024-04-14T15:42:45.729-0600] {processor.py:161} INFO - Started process (PID=4118) to work on /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:42:45.730-0600] {processor.py:830} INFO - Processing file /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T15:42:45.730-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:42:45.730-0600] {dagbag.py:540} INFO - Filling up the DagBag from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:42:45.743-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:42:45.741-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T15:42:45.743-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:42:45.743-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T15:42:45.743-0600] {processor.py:842} WARNING - No viable dags retrieved from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:42:45.770-0600] {processor.py:183} INFO - Processing /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-04-14T15:44:12.174-0600] {processor.py:161} INFO - Started process (PID=4219) to work on /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:44:12.175-0600] {processor.py:830} INFO - Processing file /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T15:44:12.176-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:44:12.176-0600] {dagbag.py:540} INFO - Filling up the DagBag from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:44:12.188-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:44:12.186-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T15:44:12.188-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:44:12.188-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T15:44:12.188-0600] {processor.py:842} WARNING - No viable dags retrieved from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:44:12.214-0600] {processor.py:183} INFO - Processing /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-04-14T15:45:40.632-0600] {processor.py:161} INFO - Started process (PID=4325) to work on /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:45:40.634-0600] {processor.py:830} INFO - Processing file /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T15:45:40.634-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:45:40.634-0600] {dagbag.py:540} INFO - Filling up the DagBag from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:45:40.646-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:45:40.645-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T15:45:40.646-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:45:40.646-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T15:45:40.646-0600] {processor.py:842} WARNING - No viable dags retrieved from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:45:40.673-0600] {processor.py:183} INFO - Processing /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-04-14T15:47:08.510-0600] {processor.py:161} INFO - Started process (PID=4425) to work on /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:47:08.512-0600] {processor.py:830} INFO - Processing file /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T15:47:08.512-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:47:08.512-0600] {dagbag.py:540} INFO - Filling up the DagBag from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:47:08.525-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:47:08.523-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T15:47:08.525-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:47:08.525-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T15:47:08.525-0600] {processor.py:842} WARNING - No viable dags retrieved from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:47:08.551-0600] {processor.py:183} INFO - Processing /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-04-14T15:48:38.548-0600] {processor.py:161} INFO - Started process (PID=4594) to work on /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:48:38.550-0600] {processor.py:830} INFO - Processing file /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T15:48:38.550-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:48:38.550-0600] {dagbag.py:540} INFO - Filling up the DagBag from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:48:38.563-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:48:38.561-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T15:48:38.563-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:48:38.563-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T15:48:38.563-0600] {processor.py:842} WARNING - No viable dags retrieved from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:48:38.589-0600] {processor.py:183} INFO - Processing /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-04-14T15:50:06.322-0600] {processor.py:161} INFO - Started process (PID=4709) to work on /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:50:06.323-0600] {processor.py:830} INFO - Processing file /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T15:50:06.323-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:50:06.323-0600] {dagbag.py:540} INFO - Filling up the DagBag from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:50:06.335-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:50:06.334-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T15:50:06.335-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:50:06.335-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T15:50:06.335-0600] {processor.py:842} WARNING - No viable dags retrieved from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:50:06.362-0600] {processor.py:183} INFO - Processing /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-04-14T15:51:37.942-0600] {processor.py:161} INFO - Started process (PID=4811) to work on /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:51:37.943-0600] {processor.py:830} INFO - Processing file /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T15:51:37.943-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:51:37.943-0600] {dagbag.py:540} INFO - Filling up the DagBag from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:51:37.956-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:51:37.954-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T15:51:37.956-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:51:37.956-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T15:51:37.956-0600] {processor.py:842} WARNING - No viable dags retrieved from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:51:37.983-0600] {processor.py:183} INFO - Processing /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-04-14T15:53:02.402-0600] {processor.py:161} INFO - Started process (PID=4967) to work on /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:53:02.404-0600] {processor.py:830} INFO - Processing file /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T15:53:02.404-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:53:02.404-0600] {dagbag.py:540} INFO - Filling up the DagBag from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:53:02.417-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:53:02.415-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T15:53:02.417-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:53:02.417-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T15:53:02.417-0600] {processor.py:842} WARNING - No viable dags retrieved from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:53:02.444-0600] {processor.py:183} INFO - Processing /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-04-14T15:54:31.165-0600] {processor.py:161} INFO - Started process (PID=5076) to work on /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:54:31.167-0600] {processor.py:830} INFO - Processing file /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T15:54:31.167-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:54:31.167-0600] {dagbag.py:540} INFO - Filling up the DagBag from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:54:31.181-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:54:31.180-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T15:54:31.181-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:54:31.181-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T15:54:31.181-0600] {processor.py:842} WARNING - No viable dags retrieved from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:54:31.208-0600] {processor.py:183} INFO - Processing /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-04-14T15:56:24.413-0600] {processor.py:161} INFO - Started process (PID=5237) to work on /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:56:24.414-0600] {processor.py:830} INFO - Processing file /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T15:56:24.415-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:56:24.414-0600] {dagbag.py:540} INFO - Filling up the DagBag from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:56:24.428-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:56:24.426-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T15:56:24.428-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:56:24.428-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T15:56:24.428-0600] {processor.py:842} WARNING - No viable dags retrieved from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:56:24.456-0600] {processor.py:183} INFO - Processing /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-04-14T15:57:48.917-0600] {processor.py:161} INFO - Started process (PID=5375) to work on /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:57:48.919-0600] {processor.py:830} INFO - Processing file /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T15:57:48.919-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:57:48.919-0600] {dagbag.py:540} INFO - Filling up the DagBag from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:57:48.932-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:57:48.930-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T15:57:48.932-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:57:48.932-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T15:57:48.932-0600] {processor.py:842} WARNING - No viable dags retrieved from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:57:48.958-0600] {processor.py:183} INFO - Processing /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-04-14T15:59:20.966-0600] {processor.py:161} INFO - Started process (PID=5500) to work on /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:59:20.967-0600] {processor.py:830} INFO - Processing file /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T15:59:20.968-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:59:20.968-0600] {dagbag.py:540} INFO - Filling up the DagBag from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:59:20.980-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:59:20.978-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T15:59:20.980-0600] {logging_mixin.py:188} INFO - [2024-04-14T15:59:20.980-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T15:59:20.980-0600] {processor.py:842} WARNING - No viable dags retrieved from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T15:59:21.006-0600] {processor.py:183} INFO - Processing /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-04-14T16:00:47.273-0600] {processor.py:161} INFO - Started process (PID=5600) to work on /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:00:47.274-0600] {processor.py:830} INFO - Processing file /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T16:00:47.274-0600] {logging_mixin.py:188} INFO - [2024-04-14T16:00:47.274-0600] {dagbag.py:540} INFO - Filling up the DagBag from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:00:47.287-0600] {logging_mixin.py:188} INFO - [2024-04-14T16:00:47.285-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T16:00:47.287-0600] {logging_mixin.py:188} INFO - [2024-04-14T16:00:47.287-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T16:00:47.287-0600] {processor.py:842} WARNING - No viable dags retrieved from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:00:47.314-0600] {processor.py:183} INFO - Processing /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-04-14T16:02:14.087-0600] {processor.py:161} INFO - Started process (PID=5698) to work on /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:02:14.089-0600] {processor.py:830} INFO - Processing file /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T16:02:14.089-0600] {logging_mixin.py:188} INFO - [2024-04-14T16:02:14.089-0600] {dagbag.py:540} INFO - Filling up the DagBag from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:02:14.102-0600] {logging_mixin.py:188} INFO - [2024-04-14T16:02:14.100-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T16:02:14.102-0600] {logging_mixin.py:188} INFO - [2024-04-14T16:02:14.102-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T16:02:14.102-0600] {processor.py:842} WARNING - No viable dags retrieved from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:02:14.129-0600] {processor.py:183} INFO - Processing /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-04-14T16:04:22.563-0600] {processor.py:161} INFO - Started process (PID=5923) to work on /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:04:22.565-0600] {processor.py:830} INFO - Processing file /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T16:04:22.565-0600] {logging_mixin.py:188} INFO - [2024-04-14T16:04:22.565-0600] {dagbag.py:540} INFO - Filling up the DagBag from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:04:22.577-0600] {logging_mixin.py:188} INFO - [2024-04-14T16:04:22.576-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T16:04:22.578-0600] {logging_mixin.py:188} INFO - [2024-04-14T16:04:22.577-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T16:04:22.578-0600] {processor.py:842} WARNING - No viable dags retrieved from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:04:22.604-0600] {processor.py:183} INFO - Processing /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-04-14T16:05:52.906-0600] {processor.py:161} INFO - Started process (PID=6087) to work on /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:05:52.907-0600] {processor.py:830} INFO - Processing file /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-04-14T16:05:52.907-0600] {logging_mixin.py:188} INFO - [2024-04-14T16:05:52.907-0600] {dagbag.py:540} INFO - Filling up the DagBag from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:05:52.920-0600] {logging_mixin.py:188} INFO - [2024-04-14T16:05:52.919-0600] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-04-14T16:05:52.920-0600] {logging_mixin.py:188} INFO - [2024-04-14T16:05:52.920-0600] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-04-14T16:05:52.920-0600] {processor.py:842} WARNING - No viable dags retrieved from /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-04-14T16:05:52.948-0600] {processor.py:183} INFO - Processing /Users/felipejimenez/Desktop/AirFlow/.env/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
